SELECT TOP (1000) [id]
      ,[email]
      ,[first_name]
      ,[last_name]
      ,[password]
      ,[role]
  FROM [testdb].[dbo].[gs_lc_mgt_user];

  ALTER TABLE gs_lc_mgt_user
ADD CONSTRAINT UNIQ_EMAIL UNIQUE (email);




CREATE TABLE GS_LCS_APP_REQUESTS (
    id INT PRIMARY KEY IDENTITY,
    REQUEST_ID VARCHAR(50) UNIQUE NOT NULL,
    REQUEST_TYPE VARCHAR(50) NOT NULL,
    REQUEST_DETAILS VARCHAR(5000),
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    INITIATED_BY VARCHAR(50),
    APPROVED_BY VARCHAR(50),
    created_at DATETIME DEFAULT GETDATE(),
    updated_at DATETIME DEFAULT GETDATE()
);


CREATE TABLE GS_LCS_APP_INTEREST_CHANGE_REQUEST(
  PK_GS_LCS_APP_INTEREST_CHANGE_REQUEST INT PRIMARY KEY IDENTITY(1,1),
  REQUEST_ID VARCHAR(50) UNIQUE NOT NULL,
  FK_PARTNER_CODE VARCHAR(50) NOT NULL,
  MIN_LOAN_VALUE BIGINT NOT NULL,
  MAX_LOAN_VALUE BIGINT NOT NULL,
  TENOR_ALL_INTEREST_RATE NUMERIC(28,2),
  TENOR_1_INTEREST_RATE NUMERIC(28,2),
  TENOR_2_INTEREST_RATE NUMERIC(28,2),
  TENOR_3_INTEREST_RATE NUMERIC(28,2),  
  TENOR_6_INTEREST_RATE NUMERIC(28,2),
  TENOR_12_INTEREST_RATE NUMERIC(28,2), 
  MAXIMUM_TENOR INT NULL,
  VALID_TENORS VARCHAR(50),
  MIN_MONTHLY_INCCOME NUMERIC(28,2) NULL,
  MAX_MONTHLY_INCCOME NUMERIC(28,2) NULL,
  MIN_AGE_YRS INT NULL,
  MAX_AGE_YRS INT NULL,
  MIDDLE_NAME_MAX_LENGTH INT NULL,
  PARTNER_ADMIN_FEE NUMERIC(28,2) NULL,
  PARTNER_ADMIN_FEE_PERCENT NUMERIC(28,2) NULL,
  CUSTOMER_SEGMENT VARCHAR(200) NULL,
  LOAN_TYPE VARCHAR(200) NULL,
  PHONE_NUMBER VARCHAR(200) NULL,
  VAT_METHOD VARCHAR(200) NULL,
  SCORE VARCHAR(200) NULL,
  RES_ADDRESS VARCHAR(25) NULL,
  LOAN_PRODUCER VARCHAR(100) NULL,
  EFFECTIVE_DATE DATETIME NOT NULL,
  JOB_TITLE VARCHAR(100) NULL,
  OCCUPATION_CODE VARCHAR(200) NULL,
  COMPANY_NAME VARCHAR(200) NULL,
  LOAN_SEGMENT VARCHAR(200) NULL,
  ACTIVE BIT NULL,
  CREATED_BY VARCHAR(50) NULL,
  LAST_UPDATED_BY VARCHAR(50) NULL,
  CREATED_DATE DATETIME DEFAULT GETDATE(),
  LAST_UPDATE_DATE DATETIME NULL
)
